# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     ProviderLookup.Repo.insert!(%ProviderLookup.SomeSchema{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.

alias ProviderLookup.Repo
alias ProviderLookup.Medical.Taxonomy
alias ProviderLookup.Medical.Npi
alias ProviderLookup.Medical.RawPl
alias ProviderLookup.Parser, as: PLParser
{:ok, _} = Application.ensure_all_started(:postgrex)
NimbleCSV.define(Parser, separator: "\t", escape: "\"")

require Logger

defmodule PLCSV do
  def save_to_taxonomy(row) do
    [
      code,
      grouping,
      classification,
      specialization,
      definition,
      effective_date,
      deactivation_date,
      last_mod_date,
      notes,
      display_name
    ] = row

    Logger.disable(self())

    Repo.insert(%Taxonomy{
      code: code,
      grouping: grouping,
      classification: classification,
      specialization: specialization,
      definition: definition,
      effective_date: effective_date,
      deactivation_date: deactivation_date,
      last_mod_date: last_mod_date,
      notes: notes,
      display_name: display_name
    })
  end

  def save_to_npi(row) do
    [
      npi,
      entity_type,
      repl_npi,
      ein,
      org_name,
      last_name,
      first_name,
      middle_name,
      name_prefix,
      name_suffix,
      credentials,
      other_org_name,
      other_org_name_type,
      other_last_name,
      other_first_name,
      other_middle_name,
      other_name_prefix,
      other_name_suffix,
      other_credential,
      other_last_name_code,
      addr_mail_first,
      addr_mail_second,
      addr_mail_city,
      addr_mail_state,
      addr_mail_postal,
      addr_mail_country,
      addr_mail_phone,
      addr_mail_fax,
      addr_practice_first,
      addr_practice_second,
      addr_practice_city,
      addr_practice_state,
      addr_practice_postal,
      addr_practice_country,
      addr_practice_phone,
      addr_practice_fax,
      enumeration_date,
      last_update,
      deactivate_reason,
      deactivate_date,
      reactivate_date,
      gender,
      off_last_name,
      off_first_name,
      off_middle_name,
      off_title,
      off_phone,
      taxonomy_1,
      license_num_1,
      license_state_1,
      taxonomy_switch_1,
      taxonomy_2,
      license_num_2,
      license_state_2,
      taxonomy_switch_2,
      taxonomy_3,
      license_num_3,
      license_state_3,
      taxonomy_switch_3,
      taxonomy_4,
      license_num_4,
      license_state_4,
      taxonomy_switch_4,
      taxonomy_5,
      license_num_5,
      license_state_5,
      taxonomy_switch_5,
      taxonomy_6,
      license_num_6,
      license_state_6,
      taxonomy_switch_6,
      taxonomy_7,
      license_num_7,
      license_state_7,
      taxonomy_switch_7,
      taxonomy_8,
      license_num_8,
      license_state_8,
      taxonomy_switch_8,
      taxonomy_9,
      license_num_9,
      license_state_9,
      taxonomy_switch_9,
      taxonomy_10,
      license_num_10,
      license_state_10,
      taxonomy_switch_10,
      taxonomy_11,
      license_num_11,
      license_state_11,
      taxonomy_switch_11,
      taxonomy_12,
      license_num_12,
      license_state_12,
      taxonomy_switch_12,
      taxonomy_13,
      license_num_13,
      license_state_13,
      taxonomy_switch_13,
      taxonomy_14,
      license_num_14,
      license_state_14,
      taxonomy_switch_14,
      taxonomy_15,
      license_num_15,
      license_state_15,
      taxonomy_switch_15,
      other_identifier_1,
      other_identifier_type_1,
      other_identifier_state_1,
      other_identifier_issuer_1,
      other_identifier_2,
      other_identifier_type_2,
      other_identifier_state_2,
      other_identifier_issuer_2,
      other_identifier_3,
      other_identifier_type_3,
      other_identifier_state_3,
      other_identifier_issuer_3,
      other_identifier_4,
      other_identifier_type_4,
      other_identifier_state_4,
      other_identifier_issuer_4,
      other_identifier_5,
      other_identifier_type_5,
      other_identifier_state_5,
      other_identifier_issuer_5,
      other_identifier_6,
      other_identifier_type_6,
      other_identifier_state_6,
      other_identifier_issuer_6,
      other_identifier_7,
      other_identifier_type_7,
      other_identifier_state_7,
      other_identifier_issuer_7,
      other_identifier_8,
      other_identifier_type_8,
      other_identifier_state_8,
      other_identifier_issuer_8,
      other_identifier_9,
      other_identifier_type_9,
      other_identifier_state_9,
      other_identifier_issuer_9,
      other_identifier_10,
      other_identifier_type_10,
      other_identifier_state_10,
      other_identifier_issuer_10,
      other_identifier_11,
      other_identifier_type_11,
      other_identifier_state_11,
      other_identifier_issuer_11,
      other_identifier_12,
      other_identifier_type_12,
      other_identifier_state_12,
      other_identifier_issuer_12,
      other_identifier_13,
      other_identifier_type_13,
      other_identifier_state_13,
      other_identifier_issuer_13,
      other_identifier_14,
      other_identifier_type_14,
      other_identifier_state_14,
      other_identifier_issuer_14,
      other_identifier_15,
      other_identifier_type_15,
      other_identifier_state_15,
      other_identifier_issuer_15,
      other_identifier_16,
      other_identifier_type_16,
      other_identifier_state_16,
      other_identifier_issuer_16,
      other_identifier_17,
      other_identifier_type_17,
      other_identifier_state_17,
      other_identifier_issuer_17,
      other_identifier_18,
      other_identifier_type_18,
      other_identifier_state_18,
      other_identifier_issuer_18,
      other_identifier_19,
      other_identifier_type_19,
      other_identifier_state_19,
      other_identifier_issuer_19,
      other_identifier_20,
      other_identifier_type_20,
      other_identifier_state_20,
      other_identifier_issuer_20,
      other_identifier_21,
      other_identifier_type_21,
      other_identifier_state_21,
      other_identifier_issuer_21,
      other_identifier_22,
      other_identifier_type_22,
      other_identifier_state_22,
      other_identifier_issuer_22,
      other_identifier_23,
      other_identifier_type_23,
      other_identifier_state_23,
      other_identifier_issuer_23,
      other_identifier_24,
      other_identifier_type_24,
      other_identifier_state_24,
      other_identifier_issuer_24,
      other_identifier_25,
      other_identifier_type_25,
      other_identifier_state_25,
      other_identifier_issuer_25,
      other_identifier_26,
      other_identifier_type_26,
      other_identifier_state_26,
      other_identifier_issuer_26,
      other_identifier_27,
      other_identifier_type_27,
      other_identifier_state_27,
      other_identifier_issuer_27,
      other_identifier_28,
      other_identifier_type_28,
      other_identifier_state_28,
      other_identifier_issuer_28,
      other_identifier_29,
      other_identifier_type_29,
      other_identifier_state_29,
      other_identifier_issuer_29,
      other_identifier_30,
      other_identifier_type_30,
      other_identifier_state_30,
      other_identifier_issuer_30,
      other_identifier_31,
      other_identifier_type_31,
      other_identifier_state_31,
      other_identifier_issuer_31,
      other_identifier_32,
      other_identifier_type_32,
      other_identifier_state_32,
      other_identifier_issuer_32,
      other_identifier_33,
      other_identifier_type_33,
      other_identifier_state_33,
      other_identifier_issuer_33,
      other_identifier_34,
      other_identifier_type_34,
      other_identifier_state_34,
      other_identifier_issuer_34,
      other_identifier_35,
      other_identifier_type_35,
      other_identifier_state_35,
      other_identifier_issuer_35,
      other_identifier_36,
      other_identifier_type_36,
      other_identifier_state_36,
      other_identifier_issuer_36,
      other_identifier_37,
      other_identifier_type_37,
      other_identifier_state_37,
      other_identifier_issuer_37,
      other_identifier_38,
      other_identifier_type_38,
      other_identifier_state_38,
      other_identifier_issuer_38,
      other_identifier_39,
      other_identifier_type_39,
      other_identifier_state_39,
      other_identifier_issuer_39,
      other_identifier_40,
      other_identifier_type_40,
      other_identifier_state_40,
      other_identifier_issuer_40,
      other_identifier_41,
      other_identifier_type_41,
      other_identifier_state_41,
      other_identifier_issuer_41,
      other_identifier_42,
      other_identifier_type_42,
      other_identifier_state_42,
      other_identifier_issuer_42,
      other_identifier_43,
      other_identifier_type_43,
      other_identifier_state_43,
      other_identifier_issuer_43,
      other_identifier_44,
      other_identifier_type_44,
      other_identifier_state_44,
      other_identifier_issuer_44,
      other_identifier_45,
      other_identifier_type_45,
      other_identifier_state_45,
      other_identifier_issuer_45,
      other_identifier_46,
      other_identifier_type_46,
      other_identifier_state_46,
      other_identifier_issuer_46,
      other_identifier_47,
      other_identifier_type_47,
      other_identifier_state_47,
      other_identifier_issuer_47,
      other_identifier_48,
      other_identifier_type_48,
      other_identifier_state_48,
      other_identifier_issuer_48,
      other_identifier_49,
      other_identifier_type_49,
      other_identifier_state_49,
      other_identifier_issuer_49,
      other_identifier_50,
      other_identifier_type_50,
      other_identifier_state_50,
      other_identifier_issuer_50,
      sole_proprieter,
      org_subpart,
      parent_lbn,
      parent_tin,
      off_name_prefix,
      off_name_suffix,
      off_credentials,
      taxonomy_group_1,
      taxonomy_group_2,
      taxonomy_group_3,
      taxonomy_group_4,
      taxonomy_group_5,
      taxonomy_group_6,
      taxonomy_group_7,
      taxonomy_group_8,
      taxonomy_group_9,
      taxonomy_group_10,
      taxonomy_group_11,
      taxonomy_group_12,
      taxonomy_group_13,
      taxonomy_group_14,
      taxonomy_group_15,
      cert_date
    ] = row

    entity_type = PLParser.parse_integer(entity_type)
    repl_npi = PLParser.parse_integer(repl_npi)
    npi = PLParser.parse_integer(npi)
    enumeration_date = PLParser.parse_date(enumeration_date)
    last_update = PLParser.parse_date(last_update)
    deactivate_date = PLParser.parse_date(deactivate_date)
    cert_date = PLParser.parse_date(cert_date)
    reactivate_date = PLParser.parse_date(reactivate_date)

    Logger.disable(self())

    Repo.insert(%Npi{
      npi: npi,
      entity_type: entity_type,
      repl_npi: repl_npi,
      ein: ein,
      org_name: org_name,
      last_name: last_name,
      first_name: first_name,
      middle_name: middle_name,
      name_prefix: name_prefix,
      name_suffix: name_suffix,
      credentials: credentials,
      other_org_name: other_org_name,
      other_org_name_type: other_org_name_type,
      other_last_name: other_last_name,
      other_first_name: other_first_name,
      other_middle_name: other_middle_name,
      other_name_prefix: other_name_prefix,
      other_name_suffix: other_name_suffix,
      other_credential: other_credential,
      other_last_name_code: other_last_name_code,
      addr_mail_first: addr_mail_first,
      addr_mail_second: addr_mail_second,
      addr_mail_city: addr_mail_city,
      addr_mail_state: addr_mail_state,
      addr_mail_postal: addr_mail_postal,
      addr_mail_country: addr_mail_country,
      addr_mail_phone: addr_mail_phone,
      addr_mail_fax: addr_mail_fax,
      addr_practice_first: addr_practice_first,
      addr_practice_second: addr_practice_second,
      addr_practice_city: addr_practice_city,
      addr_practice_state: addr_practice_state,
      addr_practice_postal: addr_practice_postal,
      addr_practice_country: addr_practice_country,
      addr_practice_phone: addr_practice_phone,
      addr_practice_fax: addr_practice_fax,
      enumeration_date: enumeration_date,
      last_update: last_update,
      deactivate_reason: deactivate_reason,
      deactivate_date: deactivate_date,
      reactivate_date: reactivate_date,
      gender: gender,
      off_last_name: off_last_name,
      off_first_name: off_first_name,
      off_middle_name: off_middle_name,
      off_title: off_title,
      off_phone: off_phone,
      taxonomy_1: taxonomy_1,
      license_num_1: license_num_1,
      license_state_1: license_state_1,
      taxonomy_switch_1: taxonomy_switch_1,
      taxonomy_2: taxonomy_2,
      license_num_2: license_num_2,
      license_state_2: license_state_2,
      taxonomy_switch_2: taxonomy_switch_2,
      taxonomy_3: taxonomy_3,
      license_num_3: license_num_3,
      license_state_3: license_state_3,
      taxonomy_switch_3: taxonomy_switch_3,
      taxonomy_4: taxonomy_4,
      license_num_4: license_num_4,
      license_state_4: license_state_4,
      taxonomy_switch_4: taxonomy_switch_4,
      taxonomy_5: taxonomy_5,
      license_num_5: license_num_5,
      license_state_5: license_state_5,
      taxonomy_switch_5: taxonomy_switch_5,
      taxonomy_6: taxonomy_6,
      license_num_6: license_num_6,
      license_state_6: license_state_6,
      taxonomy_switch_6: taxonomy_switch_6,
      taxonomy_7: taxonomy_7,
      license_num_7: license_num_7,
      license_state_7: license_state_7,
      taxonomy_switch_7: taxonomy_switch_7,
      taxonomy_8: taxonomy_8,
      license_num_8: license_num_8,
      license_state_8: license_state_8,
      taxonomy_switch_8: taxonomy_switch_8,
      taxonomy_9: taxonomy_9,
      license_num_9: license_num_9,
      license_state_9: license_state_9,
      taxonomy_switch_9: taxonomy_switch_9,
      taxonomy_10: taxonomy_10,
      license_num_10: license_num_10,
      license_state_10: license_state_10,
      taxonomy_switch_10: taxonomy_switch_10,
      taxonomy_11: taxonomy_11,
      license_num_11: license_num_11,
      license_state_11: license_state_11,
      taxonomy_switch_11: taxonomy_switch_11,
      taxonomy_12: taxonomy_12,
      license_num_12: license_num_12,
      license_state_12: license_state_12,
      taxonomy_switch_12: taxonomy_switch_12,
      taxonomy_13: taxonomy_13,
      license_num_13: license_num_13,
      license_state_13: license_state_13,
      taxonomy_switch_13: taxonomy_switch_13,
      taxonomy_14: taxonomy_14,
      license_num_14: license_num_14,
      license_state_14: license_state_14,
      taxonomy_switch_14: taxonomy_switch_14,
      taxonomy_15: taxonomy_15,
      license_num_15: license_num_15,
      license_state_15: license_state_15,
      taxonomy_switch_15: taxonomy_switch_15,
      other_identifier_1: other_identifier_1,
      other_identifier_type_1: other_identifier_type_1,
      other_identifier_state_1: other_identifier_state_1,
      other_identifier_issuer_1: other_identifier_issuer_1,
      other_identifier_2: other_identifier_2,
      other_identifier_type_2: other_identifier_type_2,
      other_identifier_state_2: other_identifier_state_2,
      other_identifier_issuer_2: other_identifier_issuer_2,
      other_identifier_3: other_identifier_3,
      other_identifier_type_3: other_identifier_type_3,
      other_identifier_state_3: other_identifier_state_3,
      other_identifier_issuer_3: other_identifier_issuer_3,
      other_identifier_4: other_identifier_4,
      other_identifier_type_4: other_identifier_type_4,
      other_identifier_state_4: other_identifier_state_4,
      other_identifier_issuer_4: other_identifier_issuer_4,
      other_identifier_5: other_identifier_5,
      other_identifier_type_5: other_identifier_type_5,
      other_identifier_state_5: other_identifier_state_5,
      other_identifier_issuer_5: other_identifier_issuer_5,
      other_identifier_6: other_identifier_6,
      other_identifier_type_6: other_identifier_type_6,
      other_identifier_state_6: other_identifier_state_6,
      other_identifier_issuer_6: other_identifier_issuer_6,
      other_identifier_7: other_identifier_7,
      other_identifier_type_7: other_identifier_type_7,
      other_identifier_state_7: other_identifier_state_7,
      other_identifier_issuer_7: other_identifier_issuer_7,
      other_identifier_8: other_identifier_8,
      other_identifier_type_8: other_identifier_type_8,
      other_identifier_state_8: other_identifier_state_8,
      other_identifier_issuer_8: other_identifier_issuer_8,
      other_identifier_9: other_identifier_9,
      other_identifier_type_9: other_identifier_type_9,
      other_identifier_state_9: other_identifier_state_9,
      other_identifier_issuer_9: other_identifier_issuer_9,
      other_identifier_10: other_identifier_10,
      other_identifier_type_10: other_identifier_type_10,
      other_identifier_state_10: other_identifier_state_10,
      other_identifier_issuer_10: other_identifier_issuer_10,
      other_identifier_11: other_identifier_11,
      other_identifier_type_11: other_identifier_type_11,
      other_identifier_state_11: other_identifier_state_11,
      other_identifier_issuer_11: other_identifier_issuer_11,
      other_identifier_12: other_identifier_12,
      other_identifier_type_12: other_identifier_type_12,
      other_identifier_state_12: other_identifier_state_12,
      other_identifier_issuer_12: other_identifier_issuer_12,
      other_identifier_13: other_identifier_13,
      other_identifier_type_13: other_identifier_type_13,
      other_identifier_state_13: other_identifier_state_13,
      other_identifier_issuer_13: other_identifier_issuer_13,
      other_identifier_14: other_identifier_14,
      other_identifier_type_14: other_identifier_type_14,
      other_identifier_state_14: other_identifier_state_14,
      other_identifier_issuer_14: other_identifier_issuer_14,
      other_identifier_15: other_identifier_15,
      other_identifier_type_15: other_identifier_type_15,
      other_identifier_state_15: other_identifier_state_15,
      other_identifier_issuer_15: other_identifier_issuer_15,
      other_identifier_16: other_identifier_16,
      other_identifier_type_16: other_identifier_type_16,
      other_identifier_state_16: other_identifier_state_16,
      other_identifier_issuer_16: other_identifier_issuer_16,
      other_identifier_17: other_identifier_17,
      other_identifier_type_17: other_identifier_type_17,
      other_identifier_state_17: other_identifier_state_17,
      other_identifier_issuer_17: other_identifier_issuer_17,
      other_identifier_18: other_identifier_18,
      other_identifier_type_18: other_identifier_type_18,
      other_identifier_state_18: other_identifier_state_18,
      other_identifier_issuer_18: other_identifier_issuer_18,
      other_identifier_19: other_identifier_19,
      other_identifier_type_19: other_identifier_type_19,
      other_identifier_state_19: other_identifier_state_19,
      other_identifier_issuer_19: other_identifier_issuer_19,
      other_identifier_20: other_identifier_20,
      other_identifier_type_20: other_identifier_type_20,
      other_identifier_state_20: other_identifier_state_20,
      other_identifier_issuer_20: other_identifier_issuer_20,
      other_identifier_21: other_identifier_21,
      other_identifier_type_21: other_identifier_type_21,
      other_identifier_state_21: other_identifier_state_21,
      other_identifier_issuer_21: other_identifier_issuer_21,
      other_identifier_22: other_identifier_22,
      other_identifier_type_22: other_identifier_type_22,
      other_identifier_state_22: other_identifier_state_22,
      other_identifier_issuer_22: other_identifier_issuer_22,
      other_identifier_23: other_identifier_23,
      other_identifier_type_23: other_identifier_type_23,
      other_identifier_state_23: other_identifier_state_23,
      other_identifier_issuer_23: other_identifier_issuer_23,
      other_identifier_24: other_identifier_24,
      other_identifier_type_24: other_identifier_type_24,
      other_identifier_state_24: other_identifier_state_24,
      other_identifier_issuer_24: other_identifier_issuer_24,
      other_identifier_25: other_identifier_25,
      other_identifier_type_25: other_identifier_type_25,
      other_identifier_state_25: other_identifier_state_25,
      other_identifier_issuer_25: other_identifier_issuer_25,
      other_identifier_26: other_identifier_26,
      other_identifier_type_26: other_identifier_type_26,
      other_identifier_state_26: other_identifier_state_26,
      other_identifier_issuer_26: other_identifier_issuer_26,
      other_identifier_27: other_identifier_27,
      other_identifier_type_27: other_identifier_type_27,
      other_identifier_state_27: other_identifier_state_27,
      other_identifier_issuer_27: other_identifier_issuer_27,
      other_identifier_28: other_identifier_28,
      other_identifier_type_28: other_identifier_type_28,
      other_identifier_state_28: other_identifier_state_28,
      other_identifier_issuer_28: other_identifier_issuer_28,
      other_identifier_29: other_identifier_29,
      other_identifier_type_29: other_identifier_type_29,
      other_identifier_state_29: other_identifier_state_29,
      other_identifier_issuer_29: other_identifier_issuer_29,
      other_identifier_30: other_identifier_30,
      other_identifier_type_30: other_identifier_type_30,
      other_identifier_state_30: other_identifier_state_30,
      other_identifier_issuer_30: other_identifier_issuer_30,
      other_identifier_31: other_identifier_31,
      other_identifier_type_31: other_identifier_type_31,
      other_identifier_state_31: other_identifier_state_31,
      other_identifier_issuer_31: other_identifier_issuer_31,
      other_identifier_32: other_identifier_32,
      other_identifier_type_32: other_identifier_type_32,
      other_identifier_state_32: other_identifier_state_32,
      other_identifier_issuer_32: other_identifier_issuer_32,
      other_identifier_33: other_identifier_33,
      other_identifier_type_33: other_identifier_type_33,
      other_identifier_state_33: other_identifier_state_33,
      other_identifier_issuer_33: other_identifier_issuer_33,
      other_identifier_34: other_identifier_34,
      other_identifier_type_34: other_identifier_type_34,
      other_identifier_state_34: other_identifier_state_34,
      other_identifier_issuer_34: other_identifier_issuer_34,
      other_identifier_35: other_identifier_35,
      other_identifier_type_35: other_identifier_type_35,
      other_identifier_state_35: other_identifier_state_35,
      other_identifier_issuer_35: other_identifier_issuer_35,
      other_identifier_36: other_identifier_36,
      other_identifier_type_36: other_identifier_type_36,
      other_identifier_state_36: other_identifier_state_36,
      other_identifier_issuer_36: other_identifier_issuer_36,
      other_identifier_37: other_identifier_37,
      other_identifier_type_37: other_identifier_type_37,
      other_identifier_state_37: other_identifier_state_37,
      other_identifier_issuer_37: other_identifier_issuer_37,
      other_identifier_38: other_identifier_38,
      other_identifier_type_38: other_identifier_type_38,
      other_identifier_state_38: other_identifier_state_38,
      other_identifier_issuer_38: other_identifier_issuer_38,
      other_identifier_39: other_identifier_39,
      other_identifier_type_39: other_identifier_type_39,
      other_identifier_state_39: other_identifier_state_39,
      other_identifier_issuer_39: other_identifier_issuer_39,
      other_identifier_40: other_identifier_40,
      other_identifier_type_40: other_identifier_type_40,
      other_identifier_state_40: other_identifier_state_40,
      other_identifier_issuer_40: other_identifier_issuer_40,
      other_identifier_41: other_identifier_41,
      other_identifier_type_41: other_identifier_type_41,
      other_identifier_state_41: other_identifier_state_41,
      other_identifier_issuer_41: other_identifier_issuer_41,
      other_identifier_42: other_identifier_42,
      other_identifier_type_42: other_identifier_type_42,
      other_identifier_state_42: other_identifier_state_42,
      other_identifier_issuer_42: other_identifier_issuer_42,
      other_identifier_43: other_identifier_43,
      other_identifier_type_43: other_identifier_type_43,
      other_identifier_state_43: other_identifier_state_43,
      other_identifier_issuer_43: other_identifier_issuer_43,
      other_identifier_44: other_identifier_44,
      other_identifier_type_44: other_identifier_type_44,
      other_identifier_state_44: other_identifier_state_44,
      other_identifier_issuer_44: other_identifier_issuer_44,
      other_identifier_45: other_identifier_45,
      other_identifier_type_45: other_identifier_type_45,
      other_identifier_state_45: other_identifier_state_45,
      other_identifier_issuer_45: other_identifier_issuer_45,
      other_identifier_46: other_identifier_46,
      other_identifier_type_46: other_identifier_type_46,
      other_identifier_state_46: other_identifier_state_46,
      other_identifier_issuer_46: other_identifier_issuer_46,
      other_identifier_47: other_identifier_47,
      other_identifier_type_47: other_identifier_type_47,
      other_identifier_state_47: other_identifier_state_47,
      other_identifier_issuer_47: other_identifier_issuer_47,
      other_identifier_48: other_identifier_48,
      other_identifier_type_48: other_identifier_type_48,
      other_identifier_state_48: other_identifier_state_48,
      other_identifier_issuer_48: other_identifier_issuer_48,
      other_identifier_49: other_identifier_49,
      other_identifier_type_49: other_identifier_type_49,
      other_identifier_state_49: other_identifier_state_49,
      other_identifier_issuer_49: other_identifier_issuer_49,
      other_identifier_50: other_identifier_50,
      other_identifier_type_50: other_identifier_type_50,
      other_identifier_state_50: other_identifier_state_50,
      other_identifier_issuer_50: other_identifier_issuer_50,
      sole_proprieter: sole_proprieter,
      org_subpart: org_subpart,
      parent_lbn: parent_lbn,
      parent_tin: parent_tin,
      off_name_prefix: off_name_prefix,
      off_name_suffix: off_name_suffix,
      off_credentials: off_credentials,
      taxonomy_group_1: taxonomy_group_1,
      taxonomy_group_2: taxonomy_group_2,
      taxonomy_group_3: taxonomy_group_3,
      taxonomy_group_4: taxonomy_group_4,
      taxonomy_group_5: taxonomy_group_5,
      taxonomy_group_6: taxonomy_group_6,
      taxonomy_group_7: taxonomy_group_7,
      taxonomy_group_8: taxonomy_group_8,
      taxonomy_group_9: taxonomy_group_9,
      taxonomy_group_10: taxonomy_group_10,
      taxonomy_group_11: taxonomy_group_11,
      taxonomy_group_12: taxonomy_group_12,
      taxonomy_group_13: taxonomy_group_13,
      taxonomy_group_14: taxonomy_group_14,
      taxonomy_group_15: taxonomy_group_15,
      cert_date: cert_date
    })
  end

  def save_to_raw_pl(row) do
    [
      npi,
      second_add_1,
      second_add_2,
      second_city,
      second_state,
      postal_code,
      country_code,
      phone,
      extension,
      fax
    ] = row

    Logger.disable(self())

    {:ok, _} =
      Repo.insert(%RawPl{
        npi: PLParser.parse_integer(npi),
        second_add_1: second_add_1,
        second_add_2: second_add_2,
        second_city: second_city,
        second_state: second_state,
        postal_code: postal_code,
        country_code: country_code,
        phone: phone,
        extension: extension,
        fax: fax
      })
  end
end

defmodule Insert do
  def taxonomy do
    IO.puts("Inserting taxonomy data")
    part_opts = [stages: System.schedulers_online()]

    {time, _} =
      :timer.tc(fn ->
        "data/taxonomy.csv"
        |> File.stream!(read_ahead: 1_000_000)
        |> NimbleCSV.RFC4180.parse_stream()
        |> Flow.from_enumerable()
        |> Flow.partition(part_opts)
        # |> Flow.partition()
        |> Flow.map(&PLCSV.save_to_taxonomy/1)
        |> Flow.run()
      end)

    Mix.shell().info([:green, "Preprocessing taxonomy in #{time / 1_000_000}s"])
  end

  def npi do
    IO.puts("Inserting npi data")

    npi_time_in_millis = :os.system_time(:millisecond)

    "data/npi.csv"
    |> File.stream!(read_ahead: 1_000_000)
    |> NimbleCSV.RFC4180.parse_stream()
    |> Flow.from_enumerable()
    |> Flow.partition()
    # |> Flow.map(&PLCSV.save_to_npi/1)
    |> Flow.map(fn [
                     npi,
                     entity_type,
                     repl_npi,
                     ein,
                     org_name,
                     last_name,
                     first_name,
                     middle_name,
                     name_prefix,
                     name_suffix,
                     credentials,
                     other_org_name,
                     other_org_name_type,
                     other_last_name,
                     other_first_name,
                     other_middle_name,
                     other_name_prefix,
                     other_name_suffix,
                     other_credential,
                     other_last_name_code,
                     addr_mail_first,
                     addr_mail_second,
                     addr_mail_city,
                     addr_mail_state,
                     addr_mail_postal,
                     addr_mail_country,
                     addr_mail_phone,
                     addr_mail_fax,
                     addr_practice_first,
                     addr_practice_second,
                     addr_practice_city,
                     addr_practice_state,
                     addr_practice_postal,
                     addr_practice_country,
                     addr_practice_phone,
                     addr_practice_fax,
                     enumeration_date,
                     last_update,
                     deactivate_reason,
                     deactivate_date,
                     reactivate_date,
                     gender,
                     off_last_name,
                     off_first_name,
                     off_middle_name,
                     off_title,
                     off_phone,
                     taxonomy_1,
                     license_num_1,
                     license_state_1,
                     taxonomy_switch_1,
                     taxonomy_2,
                     license_num_2,
                     license_state_2,
                     taxonomy_switch_2,
                     taxonomy_3,
                     license_num_3,
                     license_state_3,
                     taxonomy_switch_3,
                     taxonomy_4,
                     license_num_4,
                     license_state_4,
                     taxonomy_switch_4,
                     taxonomy_5,
                     license_num_5,
                     license_state_5,
                     taxonomy_switch_5,
                     taxonomy_6,
                     license_num_6,
                     license_state_6,
                     taxonomy_switch_6,
                     taxonomy_7,
                     license_num_7,
                     license_state_7,
                     taxonomy_switch_7,
                     taxonomy_8,
                     license_num_8,
                     license_state_8,
                     taxonomy_switch_8,
                     taxonomy_9,
                     license_num_9,
                     license_state_9,
                     taxonomy_switch_9,
                     taxonomy_10,
                     license_num_10,
                     license_state_10,
                     taxonomy_switch_10,
                     taxonomy_11,
                     license_num_11,
                     license_state_11,
                     taxonomy_switch_11,
                     taxonomy_12,
                     license_num_12,
                     license_state_12,
                     taxonomy_switch_12,
                     taxonomy_13,
                     license_num_13,
                     license_state_13,
                     taxonomy_switch_13,
                     taxonomy_14,
                     license_num_14,
                     license_state_14,
                     taxonomy_switch_14,
                     taxonomy_15,
                     license_num_15,
                     license_state_15,
                     taxonomy_switch_15,
                     other_identifier_1,
                     other_identifier_type_1,
                     other_identifier_state_1,
                     other_identifier_issuer_1,
                     other_identifier_2,
                     other_identifier_type_2,
                     other_identifier_state_2,
                     other_identifier_issuer_2,
                     other_identifier_3,
                     other_identifier_type_3,
                     other_identifier_state_3,
                     other_identifier_issuer_3,
                     other_identifier_4,
                     other_identifier_type_4,
                     other_identifier_state_4,
                     other_identifier_issuer_4,
                     other_identifier_5,
                     other_identifier_type_5,
                     other_identifier_state_5,
                     other_identifier_issuer_5,
                     other_identifier_6,
                     other_identifier_type_6,
                     other_identifier_state_6,
                     other_identifier_issuer_6,
                     other_identifier_7,
                     other_identifier_type_7,
                     other_identifier_state_7,
                     other_identifier_issuer_7,
                     other_identifier_8,
                     other_identifier_type_8,
                     other_identifier_state_8,
                     other_identifier_issuer_8,
                     other_identifier_9,
                     other_identifier_type_9,
                     other_identifier_state_9,
                     other_identifier_issuer_9,
                     other_identifier_10,
                     other_identifier_type_10,
                     other_identifier_state_10,
                     other_identifier_issuer_10,
                     other_identifier_11,
                     other_identifier_type_11,
                     other_identifier_state_11,
                     other_identifier_issuer_11,
                     other_identifier_12,
                     other_identifier_type_12,
                     other_identifier_state_12,
                     other_identifier_issuer_12,
                     other_identifier_13,
                     other_identifier_type_13,
                     other_identifier_state_13,
                     other_identifier_issuer_13,
                     other_identifier_14,
                     other_identifier_type_14,
                     other_identifier_state_14,
                     other_identifier_issuer_14,
                     other_identifier_15,
                     other_identifier_type_15,
                     other_identifier_state_15,
                     other_identifier_issuer_15,
                     other_identifier_16,
                     other_identifier_type_16,
                     other_identifier_state_16,
                     other_identifier_issuer_16,
                     other_identifier_17,
                     other_identifier_type_17,
                     other_identifier_state_17,
                     other_identifier_issuer_17,
                     other_identifier_18,
                     other_identifier_type_18,
                     other_identifier_state_18,
                     other_identifier_issuer_18,
                     other_identifier_19,
                     other_identifier_type_19,
                     other_identifier_state_19,
                     other_identifier_issuer_19,
                     other_identifier_20,
                     other_identifier_type_20,
                     other_identifier_state_20,
                     other_identifier_issuer_20,
                     other_identifier_21,
                     other_identifier_type_21,
                     other_identifier_state_21,
                     other_identifier_issuer_21,
                     other_identifier_22,
                     other_identifier_type_22,
                     other_identifier_state_22,
                     other_identifier_issuer_22,
                     other_identifier_23,
                     other_identifier_type_23,
                     other_identifier_state_23,
                     other_identifier_issuer_23,
                     other_identifier_24,
                     other_identifier_type_24,
                     other_identifier_state_24,
                     other_identifier_issuer_24,
                     other_identifier_25,
                     other_identifier_type_25,
                     other_identifier_state_25,
                     other_identifier_issuer_25,
                     other_identifier_26,
                     other_identifier_type_26,
                     other_identifier_state_26,
                     other_identifier_issuer_26,
                     other_identifier_27,
                     other_identifier_type_27,
                     other_identifier_state_27,
                     other_identifier_issuer_27,
                     other_identifier_28,
                     other_identifier_type_28,
                     other_identifier_state_28,
                     other_identifier_issuer_28,
                     other_identifier_29,
                     other_identifier_type_29,
                     other_identifier_state_29,
                     other_identifier_issuer_29,
                     other_identifier_30,
                     other_identifier_type_30,
                     other_identifier_state_30,
                     other_identifier_issuer_30,
                     other_identifier_31,
                     other_identifier_type_31,
                     other_identifier_state_31,
                     other_identifier_issuer_31,
                     other_identifier_32,
                     other_identifier_type_32,
                     other_identifier_state_32,
                     other_identifier_issuer_32,
                     other_identifier_33,
                     other_identifier_type_33,
                     other_identifier_state_33,
                     other_identifier_issuer_33,
                     other_identifier_34,
                     other_identifier_type_34,
                     other_identifier_state_34,
                     other_identifier_issuer_34,
                     other_identifier_35,
                     other_identifier_type_35,
                     other_identifier_state_35,
                     other_identifier_issuer_35,
                     other_identifier_36,
                     other_identifier_type_36,
                     other_identifier_state_36,
                     other_identifier_issuer_36,
                     other_identifier_37,
                     other_identifier_type_37,
                     other_identifier_state_37,
                     other_identifier_issuer_37,
                     other_identifier_38,
                     other_identifier_type_38,
                     other_identifier_state_38,
                     other_identifier_issuer_38,
                     other_identifier_39,
                     other_identifier_type_39,
                     other_identifier_state_39,
                     other_identifier_issuer_39,
                     other_identifier_40,
                     other_identifier_type_40,
                     other_identifier_state_40,
                     other_identifier_issuer_40,
                     other_identifier_41,
                     other_identifier_type_41,
                     other_identifier_state_41,
                     other_identifier_issuer_41,
                     other_identifier_42,
                     other_identifier_type_42,
                     other_identifier_state_42,
                     other_identifier_issuer_42,
                     other_identifier_43,
                     other_identifier_type_43,
                     other_identifier_state_43,
                     other_identifier_issuer_43,
                     other_identifier_44,
                     other_identifier_type_44,
                     other_identifier_state_44,
                     other_identifier_issuer_44,
                     other_identifier_45,
                     other_identifier_type_45,
                     other_identifier_state_45,
                     other_identifier_issuer_45,
                     other_identifier_46,
                     other_identifier_type_46,
                     other_identifier_state_46,
                     other_identifier_issuer_46,
                     other_identifier_47,
                     other_identifier_type_47,
                     other_identifier_state_47,
                     other_identifier_issuer_47,
                     other_identifier_48,
                     other_identifier_type_48,
                     other_identifier_state_48,
                     other_identifier_issuer_48,
                     other_identifier_49,
                     other_identifier_type_49,
                     other_identifier_state_49,
                     other_identifier_issuer_49,
                     other_identifier_50,
                     other_identifier_type_50,
                     other_identifier_state_50,
                     other_identifier_issuer_50,
                     sole_proprieter,
                     org_subpart,
                     parent_lbn,
                     parent_tin,
                     off_name_prefix,
                     off_name_suffix,
                     off_credentials,
                     taxonomy_group_1,
                     taxonomy_group_2,
                     taxonomy_group_3,
                     taxonomy_group_4,
                     taxonomy_group_5,
                     taxonomy_group_6,
                     taxonomy_group_7,
                     taxonomy_group_8,
                     taxonomy_group_9,
                     taxonomy_group_10,
                     taxonomy_group_11,
                     taxonomy_group_12,
                     taxonomy_group_13,
                     taxonomy_group_14,
                     taxonomy_group_15,
                     cert_date
                   ] ->
      %{
        npi: PLParser.parse_integer(npi),
        entity_type: PLParser.parse_integer(entity_type),
        repl_npi: PLParser.parse_integer(repl_npi),
        ein: ein,
        org_name: org_name,
        last_name: last_name,
        first_name: first_name,
        middle_name: middle_name,
        name_prefix: name_prefix,
        name_suffix: name_suffix,
        credentials: credentials,
        other_org_name: other_org_name,
        other_org_name_type: other_org_name_type,
        other_last_name: other_last_name,
        other_first_name: other_first_name,
        other_middle_name: other_middle_name,
        other_name_prefix: other_name_prefix,
        other_name_suffix: other_name_suffix,
        other_credential: other_credential,
        other_last_name_code: other_last_name_code,
        addr_mail_first: addr_mail_first,
        addr_mail_second: addr_mail_second,
        addr_mail_city: addr_mail_city,
        addr_mail_state: addr_mail_state,
        addr_mail_postal: addr_mail_postal,
        addr_mail_country: addr_mail_country,
        addr_mail_phone: addr_mail_phone,
        addr_mail_fax: addr_mail_fax,
        addr_practice_first: addr_practice_first,
        addr_practice_second: addr_practice_second,
        addr_practice_city: addr_practice_city,
        addr_practice_state: addr_practice_state,
        addr_practice_postal: addr_practice_postal,
        addr_practice_country: addr_practice_country,
        addr_practice_phone: addr_practice_phone,
        addr_practice_fax: addr_practice_fax,
        enumeration_date: PLParser.parse_date(enumeration_date),
        last_update: PLParser.parse_date(last_update),
        deactivate_reason: deactivate_reason,
        deactivate_date: PLParser.parse_date(deactivate_date),
        reactivate_date: PLParser.parse_date(reactivate_date),
        gender: gender,
        off_last_name: off_last_name,
        off_first_name: off_first_name,
        off_middle_name: off_middle_name,
        off_title: off_title,
        off_phone: off_phone,
        taxonomy_1: taxonomy_1,
        license_num_1: license_num_1,
        license_state_1: license_state_1,
        taxonomy_switch_1: taxonomy_switch_1,
        taxonomy_2: taxonomy_2,
        license_num_2: license_num_2,
        license_state_2: license_state_2,
        taxonomy_switch_2: taxonomy_switch_2,
        taxonomy_3: taxonomy_3,
        license_num_3: license_num_3,
        license_state_3: license_state_3,
        taxonomy_switch_3: taxonomy_switch_3,
        taxonomy_4: taxonomy_4,
        license_num_4: license_num_4,
        license_state_4: license_state_4,
        taxonomy_switch_4: taxonomy_switch_4,
        taxonomy_5: taxonomy_5,
        license_num_5: license_num_5,
        license_state_5: license_state_5,
        taxonomy_switch_5: taxonomy_switch_5,
        taxonomy_6: taxonomy_6,
        license_num_6: license_num_6,
        license_state_6: license_state_6,
        taxonomy_switch_6: taxonomy_switch_6,
        taxonomy_7: taxonomy_7,
        license_num_7: license_num_7,
        license_state_7: license_state_7,
        taxonomy_switch_7: taxonomy_switch_7,
        taxonomy_8: taxonomy_8,
        license_num_8: license_num_8,
        license_state_8: license_state_8,
        taxonomy_switch_8: taxonomy_switch_8,
        taxonomy_9: taxonomy_9,
        license_num_9: license_num_9,
        license_state_9: license_state_9,
        taxonomy_switch_9: taxonomy_switch_9,
        taxonomy_10: taxonomy_10,
        license_num_10: license_num_10,
        license_state_10: license_state_10,
        taxonomy_switch_10: taxonomy_switch_10,
        taxonomy_11: taxonomy_11,
        license_num_11: license_num_11,
        license_state_11: license_state_11,
        taxonomy_switch_11: taxonomy_switch_11,
        taxonomy_12: taxonomy_12,
        license_num_12: license_num_12,
        license_state_12: license_state_12,
        taxonomy_switch_12: taxonomy_switch_12,
        taxonomy_13: taxonomy_13,
        license_num_13: license_num_13,
        license_state_13: license_state_13,
        taxonomy_switch_13: taxonomy_switch_13,
        taxonomy_14: taxonomy_14,
        license_num_14: license_num_14,
        license_state_14: license_state_14,
        taxonomy_switch_14: taxonomy_switch_14,
        taxonomy_15: taxonomy_15,
        license_num_15: license_num_15,
        license_state_15: license_state_15,
        taxonomy_switch_15: taxonomy_switch_15,
        other_identifier_1: other_identifier_1,
        other_identifier_type_1: other_identifier_type_1,
        other_identifier_state_1: other_identifier_state_1,
        other_identifier_issuer_1: other_identifier_issuer_1,
        other_identifier_2: other_identifier_2,
        other_identifier_type_2: other_identifier_type_2,
        other_identifier_state_2: other_identifier_state_2,
        other_identifier_issuer_2: other_identifier_issuer_2,
        other_identifier_3: other_identifier_3,
        other_identifier_type_3: other_identifier_type_3,
        other_identifier_state_3: other_identifier_state_3,
        other_identifier_issuer_3: other_identifier_issuer_3,
        other_identifier_4: other_identifier_4,
        other_identifier_type_4: other_identifier_type_4,
        other_identifier_state_4: other_identifier_state_4,
        other_identifier_issuer_4: other_identifier_issuer_4,
        other_identifier_5: other_identifier_5,
        other_identifier_type_5: other_identifier_type_5,
        other_identifier_state_5: other_identifier_state_5,
        other_identifier_issuer_5: other_identifier_issuer_5,
        other_identifier_6: other_identifier_6,
        other_identifier_type_6: other_identifier_type_6,
        other_identifier_state_6: other_identifier_state_6,
        other_identifier_issuer_6: other_identifier_issuer_6,
        other_identifier_7: other_identifier_7,
        other_identifier_type_7: other_identifier_type_7,
        other_identifier_state_7: other_identifier_state_7,
        other_identifier_issuer_7: other_identifier_issuer_7,
        other_identifier_8: other_identifier_8,
        other_identifier_type_8: other_identifier_type_8,
        other_identifier_state_8: other_identifier_state_8,
        other_identifier_issuer_8: other_identifier_issuer_8,
        other_identifier_9: other_identifier_9,
        other_identifier_type_9: other_identifier_type_9,
        other_identifier_state_9: other_identifier_state_9,
        other_identifier_issuer_9: other_identifier_issuer_9,
        other_identifier_10: other_identifier_10,
        other_identifier_type_10: other_identifier_type_10,
        other_identifier_state_10: other_identifier_state_10,
        other_identifier_issuer_10: other_identifier_issuer_10,
        other_identifier_11: other_identifier_11,
        other_identifier_type_11: other_identifier_type_11,
        other_identifier_state_11: other_identifier_state_11,
        other_identifier_issuer_11: other_identifier_issuer_11,
        other_identifier_12: other_identifier_12,
        other_identifier_type_12: other_identifier_type_12,
        other_identifier_state_12: other_identifier_state_12,
        other_identifier_issuer_12: other_identifier_issuer_12,
        other_identifier_13: other_identifier_13,
        other_identifier_type_13: other_identifier_type_13,
        other_identifier_state_13: other_identifier_state_13,
        other_identifier_issuer_13: other_identifier_issuer_13,
        other_identifier_14: other_identifier_14,
        other_identifier_type_14: other_identifier_type_14,
        other_identifier_state_14: other_identifier_state_14,
        other_identifier_issuer_14: other_identifier_issuer_14,
        other_identifier_15: other_identifier_15,
        other_identifier_type_15: other_identifier_type_15,
        other_identifier_state_15: other_identifier_state_15,
        other_identifier_issuer_15: other_identifier_issuer_15,
        other_identifier_16: other_identifier_16,
        other_identifier_type_16: other_identifier_type_16,
        other_identifier_state_16: other_identifier_state_16,
        other_identifier_issuer_16: other_identifier_issuer_16,
        other_identifier_17: other_identifier_17,
        other_identifier_type_17: other_identifier_type_17,
        other_identifier_state_17: other_identifier_state_17,
        other_identifier_issuer_17: other_identifier_issuer_17,
        other_identifier_18: other_identifier_18,
        other_identifier_type_18: other_identifier_type_18,
        other_identifier_state_18: other_identifier_state_18,
        other_identifier_issuer_18: other_identifier_issuer_18,
        other_identifier_19: other_identifier_19,
        other_identifier_type_19: other_identifier_type_19,
        other_identifier_state_19: other_identifier_state_19,
        other_identifier_issuer_19: other_identifier_issuer_19,
        other_identifier_20: other_identifier_20,
        other_identifier_type_20: other_identifier_type_20,
        other_identifier_state_20: other_identifier_state_20,
        other_identifier_issuer_20: other_identifier_issuer_20,
        other_identifier_21: other_identifier_21,
        other_identifier_type_21: other_identifier_type_21,
        other_identifier_state_21: other_identifier_state_21,
        other_identifier_issuer_21: other_identifier_issuer_21,
        other_identifier_22: other_identifier_22,
        other_identifier_type_22: other_identifier_type_22,
        other_identifier_state_22: other_identifier_state_22,
        other_identifier_issuer_22: other_identifier_issuer_22,
        other_identifier_23: other_identifier_23,
        other_identifier_type_23: other_identifier_type_23,
        other_identifier_state_23: other_identifier_state_23,
        other_identifier_issuer_23: other_identifier_issuer_23,
        other_identifier_24: other_identifier_24,
        other_identifier_type_24: other_identifier_type_24,
        other_identifier_state_24: other_identifier_state_24,
        other_identifier_issuer_24: other_identifier_issuer_24,
        other_identifier_25: other_identifier_25,
        other_identifier_type_25: other_identifier_type_25,
        other_identifier_state_25: other_identifier_state_25,
        other_identifier_issuer_25: other_identifier_issuer_25,
        other_identifier_26: other_identifier_26,
        other_identifier_type_26: other_identifier_type_26,
        other_identifier_state_26: other_identifier_state_26,
        other_identifier_issuer_26: other_identifier_issuer_26,
        other_identifier_27: other_identifier_27,
        other_identifier_type_27: other_identifier_type_27,
        other_identifier_state_27: other_identifier_state_27,
        other_identifier_issuer_27: other_identifier_issuer_27,
        other_identifier_28: other_identifier_28,
        other_identifier_type_28: other_identifier_type_28,
        other_identifier_state_28: other_identifier_state_28,
        other_identifier_issuer_28: other_identifier_issuer_28,
        other_identifier_29: other_identifier_29,
        other_identifier_type_29: other_identifier_type_29,
        other_identifier_state_29: other_identifier_state_29,
        other_identifier_issuer_29: other_identifier_issuer_29,
        other_identifier_30: other_identifier_30,
        other_identifier_type_30: other_identifier_type_30,
        other_identifier_state_30: other_identifier_state_30,
        other_identifier_issuer_30: other_identifier_issuer_30,
        other_identifier_31: other_identifier_31,
        other_identifier_type_31: other_identifier_type_31,
        other_identifier_state_31: other_identifier_state_31,
        other_identifier_issuer_31: other_identifier_issuer_31,
        other_identifier_32: other_identifier_32,
        other_identifier_type_32: other_identifier_type_32,
        other_identifier_state_32: other_identifier_state_32,
        other_identifier_issuer_32: other_identifier_issuer_32,
        other_identifier_33: other_identifier_33,
        other_identifier_type_33: other_identifier_type_33,
        other_identifier_state_33: other_identifier_state_33,
        other_identifier_issuer_33: other_identifier_issuer_33,
        other_identifier_34: other_identifier_34,
        other_identifier_type_34: other_identifier_type_34,
        other_identifier_state_34: other_identifier_state_34,
        other_identifier_issuer_34: other_identifier_issuer_34,
        other_identifier_35: other_identifier_35,
        other_identifier_type_35: other_identifier_type_35,
        other_identifier_state_35: other_identifier_state_35,
        other_identifier_issuer_35: other_identifier_issuer_35,
        other_identifier_36: other_identifier_36,
        other_identifier_type_36: other_identifier_type_36,
        other_identifier_state_36: other_identifier_state_36,
        other_identifier_issuer_36: other_identifier_issuer_36,
        other_identifier_37: other_identifier_37,
        other_identifier_type_37: other_identifier_type_37,
        other_identifier_state_37: other_identifier_state_37,
        other_identifier_issuer_37: other_identifier_issuer_37,
        other_identifier_38: other_identifier_38,
        other_identifier_type_38: other_identifier_type_38,
        other_identifier_state_38: other_identifier_state_38,
        other_identifier_issuer_38: other_identifier_issuer_38,
        other_identifier_39: other_identifier_39,
        other_identifier_type_39: other_identifier_type_39,
        other_identifier_state_39: other_identifier_state_39,
        other_identifier_issuer_39: other_identifier_issuer_39,
        other_identifier_40: other_identifier_40,
        other_identifier_type_40: other_identifier_type_40,
        other_identifier_state_40: other_identifier_state_40,
        other_identifier_issuer_40: other_identifier_issuer_40,
        other_identifier_41: other_identifier_41,
        other_identifier_type_41: other_identifier_type_41,
        other_identifier_state_41: other_identifier_state_41,
        other_identifier_issuer_41: other_identifier_issuer_41,
        other_identifier_42: other_identifier_42,
        other_identifier_type_42: other_identifier_type_42,
        other_identifier_state_42: other_identifier_state_42,
        other_identifier_issuer_42: other_identifier_issuer_42,
        other_identifier_43: other_identifier_43,
        other_identifier_type_43: other_identifier_type_43,
        other_identifier_state_43: other_identifier_state_43,
        other_identifier_issuer_43: other_identifier_issuer_43,
        other_identifier_44: other_identifier_44,
        other_identifier_type_44: other_identifier_type_44,
        other_identifier_state_44: other_identifier_state_44,
        other_identifier_issuer_44: other_identifier_issuer_44,
        other_identifier_45: other_identifier_45,
        other_identifier_type_45: other_identifier_type_45,
        other_identifier_state_45: other_identifier_state_45,
        other_identifier_issuer_45: other_identifier_issuer_45,
        other_identifier_46: other_identifier_46,
        other_identifier_type_46: other_identifier_type_46,
        other_identifier_state_46: other_identifier_state_46,
        other_identifier_issuer_46: other_identifier_issuer_46,
        other_identifier_47: other_identifier_47,
        other_identifier_type_47: other_identifier_type_47,
        other_identifier_state_47: other_identifier_state_47,
        other_identifier_issuer_47: other_identifier_issuer_47,
        other_identifier_48: other_identifier_48,
        other_identifier_type_48: other_identifier_type_48,
        other_identifier_state_48: other_identifier_state_48,
        other_identifier_issuer_48: other_identifier_issuer_48,
        other_identifier_49: other_identifier_49,
        other_identifier_type_49: other_identifier_type_49,
        other_identifier_state_49: other_identifier_state_49,
        other_identifier_issuer_49: other_identifier_issuer_49,
        other_identifier_50: other_identifier_50,
        other_identifier_type_50: other_identifier_type_50,
        other_identifier_state_50: other_identifier_state_50,
        other_identifier_issuer_50: other_identifier_issuer_50,
        sole_proprieter: sole_proprieter,
        org_subpart: org_subpart,
        parent_lbn: parent_lbn,
        parent_tin: parent_tin,
        off_name_prefix: off_name_prefix,
        off_name_suffix: off_name_suffix,
        off_credentials: off_credentials,
        taxonomy_group_1: taxonomy_group_1,
        taxonomy_group_2: taxonomy_group_2,
        taxonomy_group_3: taxonomy_group_3,
        taxonomy_group_4: taxonomy_group_4,
        taxonomy_group_5: taxonomy_group_5,
        taxonomy_group_6: taxonomy_group_6,
        taxonomy_group_7: taxonomy_group_7,
        taxonomy_group_8: taxonomy_group_8,
        taxonomy_group_9: taxonomy_group_9,
        taxonomy_group_10: taxonomy_group_10,
        taxonomy_group_11: taxonomy_group_11,
        taxonomy_group_12: taxonomy_group_12,
        taxonomy_group_13: taxonomy_group_13,
        taxonomy_group_14: taxonomy_group_14,
        taxonomy_group_15: taxonomy_group_15,
        cert_date: PLParser.parse_date(cert_date)
      }
    end)
    |> Flow.partition(key: {:key, :npi}, stages: 8)
    |> Flow.reduce(fn -> :ets.new(:npis, []) end, fn row, table ->
      Logger.disable(self())

      Repo.insert(%Npi{
        npi: row[:npi],
        entity_type: row[:entity_type],
        repl_npi: row[:repl_npi],
        ein: row[:ein],
        org_name: row[:org_name],
        last_name: row[:last_name],
        first_name: row[:first_name],
        middle_name: row[:middle_name],
        name_prefix: row[:name_prefix],
        name_suffix: row[:name_suffix],
        credentials: row[:credentials],
        other_org_name: row[:other_org_name],
        other_org_name_type: row[:other_org_name_type],
        other_last_name: row[:other_last_name],
        other_first_name: row[:other_first_name],
        other_middle_name: row[:other_middle_name],
        other_name_prefix: row[:other_name_prefix],
        other_name_suffix: row[:other_name_suffix],
        other_credential: row[:other_credential],
        other_last_name_code: row[:other_last_name_code],
        addr_mail_first: row[:addr_mail_first],
        addr_mail_second: row[:addr_mail_second],
        addr_mail_city: row[:addr_mail_city],
        addr_mail_state: row[:addr_mail_state],
        addr_mail_postal: row[:addr_mail_postal],
        addr_mail_country: row[:addr_mail_country],
        addr_mail_phone: row[:addr_mail_phone],
        addr_mail_fax: row[:addr_mail_fax],
        addr_practice_first: row[:addr_practice_first],
        addr_practice_second: row[:addr_practice_second],
        addr_practice_city: row[:addr_practice_city],
        addr_practice_state: row[:addr_practice_state],
        addr_practice_postal: row[:addr_practice_postal],
        addr_practice_country: row[:addr_practice_country],
        addr_practice_phone: row[:addr_practice_phone],
        addr_practice_fax: row[:addr_practice_fax],
        enumeration_date: row[:enumeration_date],
        last_update: row[:last_update],
        deactivate_reason: row[:deactivate_reason],
        deactivate_date: row[:deactivate_date],
        reactivate_date: row[:reactivate_date],
        gender: row[:gender],
        off_last_name: row[:off_last_name],
        off_first_name: row[:off_first_name],
        off_middle_name: row[:off_middle_name],
        off_title: row[:off_title],
        off_phone: row[:off_phone],
        taxonomy_1: row[:taxonomy_1],
        license_num_1: row[:license_num_1],
        license_state_1: row[:license_state_1],
        taxonomy_switch_1: row[:taxonomy_switch_1],
        taxonomy_2: row[:taxonomy_2],
        license_num_2: row[:license_num_2],
        license_state_2: row[:license_state_2],
        taxonomy_switch_2: row[:taxonomy_switch_2],
        taxonomy_3: row[:taxonomy_3],
        license_num_3: row[:license_num_3],
        license_state_3: row[:license_state_3],
        taxonomy_switch_3: row[:taxonomy_switch_3],
        taxonomy_4: row[:taxonomy_4],
        license_num_4: row[:license_num_4],
        license_state_4: row[:license_state_4],
        taxonomy_switch_4: row[:taxonomy_switch_4],
        taxonomy_5: row[:taxonomy_5],
        license_num_5: row[:license_num_5],
        license_state_5: row[:license_state_5],
        taxonomy_switch_5: row[:taxonomy_switch_5],
        taxonomy_6: row[:taxonomy_6],
        license_num_6: row[:license_num_6],
        license_state_6: row[:license_state_6],
        taxonomy_switch_6: row[:taxonomy_switch_6],
        taxonomy_7: row[:taxonomy_7],
        license_num_7: row[:license_num_7],
        license_state_7: row[:license_state_7],
        taxonomy_switch_7: row[:taxonomy_switch_7],
        taxonomy_8: row[:taxonomy_8],
        license_num_8: row[:license_num_8],
        license_state_8: row[:license_state_8],
        taxonomy_switch_8: row[:taxonomy_switch_8],
        taxonomy_9: row[:taxonomy_9],
        license_num_9: row[:license_num_9],
        license_state_9: row[:license_state_9],
        taxonomy_switch_9: row[:taxonomy_switch_9],
        taxonomy_10: row[:taxonomy_10],
        license_num_10: row[:license_num_10],
        license_state_10: row[:license_state_10],
        taxonomy_switch_10: row[:taxonomy_switch_10],
        taxonomy_11: row[:taxonomy_11],
        license_num_11: row[:license_num_11],
        license_state_11: row[:license_state_11],
        taxonomy_switch_11: row[:taxonomy_switch_11],
        taxonomy_12: row[:taxonomy_12],
        license_num_12: row[:license_num_12],
        license_state_12: row[:license_state_12],
        taxonomy_switch_12: row[:taxonomy_switch_12],
        taxonomy_13: row[:taxonomy_13],
        license_num_13: row[:license_num_13],
        license_state_13: row[:license_state_13],
        taxonomy_switch_13: row[:taxonomy_switch_13],
        taxonomy_14: row[:taxonomy_14],
        license_num_14: row[:license_num_14],
        license_state_14: row[:license_state_14],
        taxonomy_switch_14: row[:taxonomy_switch_14],
        taxonomy_15: row[:taxonomy_15],
        license_num_15: row[:license_num_15],
        license_state_15: row[:license_state_15],
        taxonomy_switch_15: row[:taxonomy_switch_15],
        other_identifier_1: row[:other_identifier_1],
        other_identifier_type_1: row[:other_identifier_type_1],
        other_identifier_state_1: row[:other_identifier_state_1],
        other_identifier_issuer_1: row[:other_identifier_issuer_1],
        other_identifier_2: row[:other_identifier_2],
        other_identifier_type_2: row[:other_identifier_type_2],
        other_identifier_state_2: row[:other_identifier_state_2],
        other_identifier_issuer_2: row[:other_identifier_issuer_2],
        other_identifier_3: row[:other_identifier_3],
        other_identifier_type_3: row[:other_identifier_type_3],
        other_identifier_state_3: row[:other_identifier_state_3],
        other_identifier_issuer_3: row[:other_identifier_issuer_3],
        other_identifier_4: row[:other_identifier_4],
        other_identifier_type_4: row[:other_identifier_type_4],
        other_identifier_state_4: row[:other_identifier_state_4],
        other_identifier_issuer_4: row[:other_identifier_issuer_4],
        other_identifier_5: row[:other_identifier_5],
        other_identifier_type_5: row[:other_identifier_type_5],
        other_identifier_state_5: row[:other_identifier_state_5],
        other_identifier_issuer_5: row[:other_identifier_issuer_5],
        other_identifier_6: row[:other_identifier_6],
        other_identifier_type_6: row[:other_identifier_type_6],
        other_identifier_state_6: row[:other_identifier_state_6],
        other_identifier_issuer_6: row[:other_identifier_issuer_6],
        other_identifier_7: row[:other_identifier_7],
        other_identifier_type_7: row[:other_identifier_type_7],
        other_identifier_state_7: row[:other_identifier_state_7],
        other_identifier_issuer_7: row[:other_identifier_issuer_7],
        other_identifier_8: row[:other_identifier_8],
        other_identifier_type_8: row[:other_identifier_type_8],
        other_identifier_state_8: row[:other_identifier_state_8],
        other_identifier_issuer_8: row[:other_identifier_issuer_8],
        other_identifier_9: row[:other_identifier_9],
        other_identifier_type_9: row[:other_identifier_type_9],
        other_identifier_state_9: row[:other_identifier_state_9],
        other_identifier_issuer_9: row[:other_identifier_issuer_9],
        other_identifier_10: row[:other_identifier_10],
        other_identifier_type_10: row[:other_identifier_type_10],
        other_identifier_state_10: row[:other_identifier_state_10],
        other_identifier_issuer_10: row[:other_identifier_issuer_10],
        other_identifier_11: row[:other_identifier_11],
        other_identifier_type_11: row[:other_identifier_type_11],
        other_identifier_state_11: row[:other_identifier_state_11],
        other_identifier_issuer_11: row[:other_identifier_issuer_11],
        other_identifier_12: row[:other_identifier_12],
        other_identifier_type_12: row[:other_identifier_type_12],
        other_identifier_state_12: row[:other_identifier_state_12],
        other_identifier_issuer_12: row[:other_identifier_issuer_12],
        other_identifier_13: row[:other_identifier_13],
        other_identifier_type_13: row[:other_identifier_type_13],
        other_identifier_state_13: row[:other_identifier_state_13],
        other_identifier_issuer_13: row[:other_identifier_issuer_13],
        other_identifier_14: row[:other_identifier_14],
        other_identifier_type_14: row[:other_identifier_type_14],
        other_identifier_state_14: row[:other_identifier_state_14],
        other_identifier_issuer_14: row[:other_identifier_issuer_14],
        other_identifier_15: row[:other_identifier_15],
        other_identifier_type_15: row[:other_identifier_type_15],
        other_identifier_state_15: row[:other_identifier_state_15],
        other_identifier_issuer_15: row[:other_identifier_issuer_15],
        other_identifier_16: row[:other_identifier_16],
        other_identifier_type_16: row[:other_identifier_type_16],
        other_identifier_state_16: row[:other_identifier_state_16],
        other_identifier_issuer_16: row[:other_identifier_issuer_16],
        other_identifier_17: row[:other_identifier_17],
        other_identifier_type_17: row[:other_identifier_type_17],
        other_identifier_state_17: row[:other_identifier_state_17],
        other_identifier_issuer_17: row[:other_identifier_issuer_17],
        other_identifier_18: row[:other_identifier_18],
        other_identifier_type_18: row[:other_identifier_type_18],
        other_identifier_state_18: row[:other_identifier_state_18],
        other_identifier_issuer_18: row[:other_identifier_issuer_18],
        other_identifier_19: row[:other_identifier_19],
        other_identifier_type_19: row[:other_identifier_type_19],
        other_identifier_state_19: row[:other_identifier_state_19],
        other_identifier_issuer_19: row[:other_identifier_issuer_19],
        other_identifier_20: row[:other_identifier_20],
        other_identifier_type_20: row[:other_identifier_type_20],
        other_identifier_state_20: row[:other_identifier_state_20],
        other_identifier_issuer_20: row[:other_identifier_issuer_20],
        other_identifier_21: row[:other_identifier_21],
        other_identifier_type_21: row[:other_identifier_type_21],
        other_identifier_state_21: row[:other_identifier_state_21],
        other_identifier_issuer_21: row[:other_identifier_issuer_21],
        other_identifier_22: row[:other_identifier_22],
        other_identifier_type_22: row[:other_identifier_type_22],
        other_identifier_state_22: row[:other_identifier_state_22],
        other_identifier_issuer_22: row[:other_identifier_issuer_22],
        other_identifier_23: row[:other_identifier_23],
        other_identifier_type_23: row[:other_identifier_type_23],
        other_identifier_state_23: row[:other_identifier_state_23],
        other_identifier_issuer_23: row[:other_identifier_issuer_23],
        other_identifier_24: row[:other_identifier_24],
        other_identifier_type_24: row[:other_identifier_type_24],
        other_identifier_state_24: row[:other_identifier_state_24],
        other_identifier_issuer_24: row[:other_identifier_issuer_24],
        other_identifier_25: row[:other_identifier_25],
        other_identifier_type_25: row[:other_identifier_type_25],
        other_identifier_state_25: row[:other_identifier_state_25],
        other_identifier_issuer_25: row[:other_identifier_issuer_25],
        other_identifier_26: row[:other_identifier_26],
        other_identifier_type_26: row[:other_identifier_type_26],
        other_identifier_state_26: row[:other_identifier_state_26],
        other_identifier_issuer_26: row[:other_identifier_issuer_26],
        other_identifier_27: row[:other_identifier_27],
        other_identifier_type_27: row[:other_identifier_type_27],
        other_identifier_state_27: row[:other_identifier_state_27],
        other_identifier_issuer_27: row[:other_identifier_issuer_27],
        other_identifier_28: row[:other_identifier_28],
        other_identifier_type_28: row[:other_identifier_type_28],
        other_identifier_state_28: row[:other_identifier_state_28],
        other_identifier_issuer_28: row[:other_identifier_issuer_28],
        other_identifier_29: row[:other_identifier_29],
        other_identifier_type_29: row[:other_identifier_type_29],
        other_identifier_state_29: row[:other_identifier_state_29],
        other_identifier_issuer_29: row[:other_identifier_issuer_29],
        other_identifier_30: row[:other_identifier_30],
        other_identifier_type_30: row[:other_identifier_type_30],
        other_identifier_state_30: row[:other_identifier_state_30],
        other_identifier_issuer_30: row[:other_identifier_issuer_30],
        other_identifier_31: row[:other_identifier_31],
        other_identifier_type_31: row[:other_identifier_type_31],
        other_identifier_state_31: row[:other_identifier_state_31],
        other_identifier_issuer_31: row[:other_identifier_issuer_31],
        other_identifier_32: row[:other_identifier_32],
        other_identifier_type_32: row[:other_identifier_type_32],
        other_identifier_state_32: row[:other_identifier_state_32],
        other_identifier_issuer_32: row[:other_identifier_issuer_32],
        other_identifier_33: row[:other_identifier_33],
        other_identifier_type_33: row[:other_identifier_type_33],
        other_identifier_state_33: row[:other_identifier_state_33],
        other_identifier_issuer_33: row[:other_identifier_issuer_33],
        other_identifier_34: row[:other_identifier_34],
        other_identifier_type_34: row[:other_identifier_type_34],
        other_identifier_state_34: row[:other_identifier_state_34],
        other_identifier_issuer_34: row[:other_identifier_issuer_34],
        other_identifier_35: row[:other_identifier_35],
        other_identifier_type_35: row[:other_identifier_type_35],
        other_identifier_state_35: row[:other_identifier_state_35],
        other_identifier_issuer_35: row[:other_identifier_issuer_35],
        other_identifier_36: row[:other_identifier_36],
        other_identifier_type_36: row[:other_identifier_type_36],
        other_identifier_state_36: row[:other_identifier_state_36],
        other_identifier_issuer_36: row[:other_identifier_issuer_36],
        other_identifier_37: row[:other_identifier_37],
        other_identifier_type_37: row[:other_identifier_type_37],
        other_identifier_state_37: row[:other_identifier_state_37],
        other_identifier_issuer_37: row[:other_identifier_issuer_37],
        other_identifier_38: row[:other_identifier_38],
        other_identifier_type_38: row[:other_identifier_type_38],
        other_identifier_state_38: row[:other_identifier_state_38],
        other_identifier_issuer_38: row[:other_identifier_issuer_38],
        other_identifier_39: row[:other_identifier_39],
        other_identifier_type_39: row[:other_identifier_type_39],
        other_identifier_state_39: row[:other_identifier_state_39],
        other_identifier_issuer_39: row[:other_identifier_issuer_39],
        other_identifier_40: row[:other_identifier_40],
        other_identifier_type_40: row[:other_identifier_type_40],
        other_identifier_state_40: row[:other_identifier_state_40],
        other_identifier_issuer_40: row[:other_identifier_issuer_40],
        other_identifier_41: row[:other_identifier_41],
        other_identifier_type_41: row[:other_identifier_type_41],
        other_identifier_state_41: row[:other_identifier_state_41],
        other_identifier_issuer_41: row[:other_identifier_issuer_41],
        other_identifier_42: row[:other_identifier_42],
        other_identifier_type_42: row[:other_identifier_type_42],
        other_identifier_state_42: row[:other_identifier_state_42],
        other_identifier_issuer_42: row[:other_identifier_issuer_42],
        other_identifier_43: row[:other_identifier_43],
        other_identifier_type_43: row[:other_identifier_type_43],
        other_identifier_state_43: row[:other_identifier_state_43],
        other_identifier_issuer_43: row[:other_identifier_issuer_43],
        other_identifier_44: row[:other_identifier_44],
        other_identifier_type_44: row[:other_identifier_type_44],
        other_identifier_state_44: row[:other_identifier_state_44],
        other_identifier_issuer_44: row[:other_identifier_issuer_44],
        other_identifier_45: row[:other_identifier_45],
        other_identifier_type_45: row[:other_identifier_type_45],
        other_identifier_state_45: row[:other_identifier_state_45],
        other_identifier_issuer_45: row[:other_identifier_issuer_45],
        other_identifier_46: row[:other_identifier_46],
        other_identifier_type_46: row[:other_identifier_type_46],
        other_identifier_state_46: row[:other_identifier_state_46],
        other_identifier_issuer_46: row[:other_identifier_issuer_46],
        other_identifier_47: row[:other_identifier_47],
        other_identifier_type_47: row[:other_identifier_type_47],
        other_identifier_state_47: row[:other_identifier_state_47],
        other_identifier_issuer_47: row[:other_identifier_issuer_47],
        other_identifier_48: row[:other_identifier_48],
        other_identifier_type_48: row[:other_identifier_type_48],
        other_identifier_state_48: row[:other_identifier_state_48],
        other_identifier_issuer_48: row[:other_identifier_issuer_48],
        other_identifier_49: row[:other_identifier_49],
        other_identifier_type_49: row[:other_identifier_type_49],
        other_identifier_state_49: row[:other_identifier_state_49],
        other_identifier_issuer_49: row[:other_identifier_issuer_49],
        other_identifier_50: row[:other_identifier_50],
        other_identifier_type_50: row[:other_identifier_type_50],
        other_identifier_state_50: row[:other_identifier_state_50],
        other_identifier_issuer_50: row[:other_identifier_issuer_50],
        sole_proprieter: row[:sole_proprieter],
        org_subpart: row[:org_subpart],
        parent_lbn: row[:parent_lbn],
        parent_tin: row[:parent_tin],
        off_name_prefix: row[:off_name_prefix],
        off_name_suffix: row[:off_name_suffix],
        off_credentials: row[:off_credentials],
        taxonomy_group_1: row[:taxonomy_group_1],
        taxonomy_group_2: row[:taxonomy_group_2],
        taxonomy_group_3: row[:taxonomy_group_3],
        taxonomy_group_4: row[:taxonomy_group_4],
        taxonomy_group_5: row[:taxonomy_group_5],
        taxonomy_group_6: row[:taxonomy_group_6],
        taxonomy_group_7: row[:taxonomy_group_7],
        taxonomy_group_8: row[:taxonomy_group_8],
        taxonomy_group_9: row[:taxonomy_group_9],
        taxonomy_group_10: row[:taxonomy_group_10],
        taxonomy_group_11: row[:taxonomy_group_11],
        taxonomy_group_12: row[:taxonomy_group_12],
        taxonomy_group_13: row[:taxonomy_group_13],
        taxonomy_group_14: row[:taxonomy_group_14],
        taxonomy_group_15: row[:taxonomy_group_15],
        cert_date: row[:cert_date]
      })

      table
    end)
    |> Flow.run()

    Mix.shell().info([
      :green,
      "Preprocessing npi done in #{(:os.system_time(:millisecond) - npi_time_in_millis) / 60000}m"
    ])
  end

  def npi_taxonomy do
    IO.puts("Copy data from npi, taxonomy into npi_taxonomy table")
    npi_taxonomy_time_in_millis = :os.system_time(:millisecond)

    Repo.query(
      """
      DO $$
      DECLARE counter integer := 1;
      BEGIN
          WHILE ( counter <= 15 ) LOOP
            -- Insert all taxonomy columns separately into taxonomy tables
            EXECUTE format('INSERT INTO npi_taxonomy(npi,taxonomy,taxonomy_group,taxonomy_classification,license_num,license_state,taxonomy_switch)
            SELECT npi.npi, npi.taxonomy_%s, npi.taxonomy_group_%s, taxonomy.classification, npi.license_num_%s, npi.license_state_%s, npi.taxonomy_switch_%s
            FROM npi, taxonomy
            WHERE taxonomy_%s IS NOT NULL AND npi.taxonomy_%s = taxonomy.code', counter, counter, counter, counter, counter, counter, counter);
            -- Increment counter
            counter := counter + 1;
          END LOOP;
      END $$
      """,
      []
    )

    Mix.shell().info([
      :green,
      "Preprocessing npi taxonomy done in #{(:os.system_time(:millisecond) - npi_taxonomy_time_in_millis) / 60000}m"
    ])
  end

  def raw_pl do
    IO.puts("Copy data from pl into raw pl table")
    raw_pl_time_in_millis = :os.system_time(:millisecond)

    "data/pl.csv"
    |> File.stream!(read_ahead: 1_000_000)
    |> NimbleCSV.RFC4180.parse_stream()
    |> Flow.from_enumerable()
    |> Flow.partition()
    |> Flow.map(&PLCSV.save_to_raw_pl/1)
    |> Flow.run()

    Mix.shell().info([
      :green,
      "Preprocessing pl done in #{(:os.system_time(:millisecond) - raw_pl_time_in_millis) / 60000}m"
    ])
  end

  def addresses_1 do
    IO.puts("Copy data from npi into addresses table")
    addresses1_in_millis = :os.system_time(:millisecond)

    Repo.query(
      "
INSERT INTO addresses(npi,line_1,line_2,city,state,postal,country,phone,fax)
SELECT npi,addr_practice_first,addr_practice_second,addr_practice_city,addr_practice_state,addr_practice_postal,addr_practice_country,addr_practice_phone,addr_practice_fax
FROM npi
WHERE addr_practice_first IS NOT NULL;
",
      []
    )

    Mix.shell().info([
      :green,
      "Preprocessing pl done in #{(:os.system_time(:millisecond) - addresses1_in_millis) / 60000}m"
    ])
  end

  def addresses_2 do
    IO.puts("Copy data from raw pl into addresses table")
    addresses2_in_millis = :os.system_time(:millisecond)

    Repo.query(
      "
INSERT INTO addresses(npi,line_1,line_2,city,state,postal,country,phone,fax)
SELECT npi,second_add_1,second_add_2,second_city,second_state,postal_code,country_code,phone,fax
FROM raw_pl;
",
      []
    )

    Mix.shell().info([
      :green,
      "Preprocessing pl done in #{(:os.system_time(:millisecond) - addresses2_in_millis) / 60000}m"
    ])
  end

  def core_npi do
    IO.puts("Insert data into core_npi table")
    core_npi_in_millis = :os.system_time(:millisecond)

    Repo.query(
      "
INSERT INTO core_npi(npi, last_name, first_name, description, state, city, zip, addr_first, addr_last, phone)
SELECT npi.npi, npi.last_name, npi.first_name, upper(npi_taxonomy.taxonomy_classification), upper(addresses.state), upper(addresses.city),
       LEFT(addresses.postal, 5), upper(addresses.line_1), upper(addresses.line_2), addresses.phone
FROM npi
INNER JOIN addresses
ON npi.npi = addresses.npi
INNER JOIN npi_taxonomy
ON npi.npi = npi_taxonomy.npi
WHERE npi.last_name IS NOT NULL AND npi_taxonomy.taxonomy_switch = 'Y';
",
      []
    )

    Mix.shell().info([
      :green,
      "Preprocessing core npi done in #{(:os.system_time(:millisecond) - core_npi_in_millis) / 60000}m"
    ])
  end
end

Insert.taxonomy()
Insert.npi()
Insert.npi_taxonomy()
Insert.raw_pl()
Insert.addresses_1()
Insert.addresses_2()
Insert.core_npi()
